### ISSUE TITLE
(Not Bug related) Question / request: Any plan to update skirl with physic weight paint? 

### ISSUE THREAD

**Issue by KaitoXion** [KingEnderBrine/-RoR2-Mercenary2B#3]
A humble question / request: Any plan to update skirt with physic weight paint?

This current skirt looks pretty fat and quite weird. Didn't makes sense most of the time.
Just saying. The design is great though.
Nothing much to say aside from thank you.

**Comment by KingEnderBrine** [comment]
Hello, no, I have no intentions to update the mod unless it stops working on the latest game version

**Comment by KaitoXion** [comment]
I see.
Thank you for your creation. Appreciate your kind reply. 👍



2023年11月9日(木) 1:22 KingEnderBrine ***@***.***>:
