### ISSUE TITLE
bug and request

### ISSUE THREAD

**Issue by Nakimor** [KingEnderBrine/-RoR2-Mercenary2B#4]
With the new update, the model broke and I would really like to disable the skirt in the config (maybe you should hold off on updating until the DLS is released)

**Comment by KingEnderBrine** [comment]
Dlc is most likely will not be soon, though I will take some time to play the update before fixing any of my mods

**Comment by KingEnderBrine** [comment]
Published an update with a fix and added the config option

**Comment by Nakimor** [comment]
I love you, thank you. ❤
